[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_escrow_2023 = "E8YJXy9iYuKYK9GDn8GJoPyKHCJR4eT3jWAyGq6RArXc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/tiosam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
