[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "ANWZywNbnqNqrXxz2Vv79QLtDqW4BQL4iUyaz26whbdX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tiosam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
